site_name: Album
site_url: http://127.0.0.1:8001/rcs
copyright: Copyright &copy; 2024-2025 Jakob Adams.
theme:
  language: de
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
#    - navigation.tabs
    - navigation.indexes
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode


plugins:
  - search
  - offline
  - macros
  - exporter:
      enabled: false
      logging:
        level: debug
      formats:
        pdf:
          concurrency: 1
          stylesheets:
            - docs/assets/stylesheets/pdf.scss
          covers:
            front: docs/assets/covers/front.html.j2
            back: docs/assets/covers/back.html.j2
          browser:
            debug: false
          aggregator:
            enabled: true
            output: documentation.pdf
            covers: book

markdown_extensions:
  - toc:
      permalink: false
  - admonition
  - footnotes
  - def_list
  - attr_list
  - pymdownx.blocks.caption

extra:
  project_name: Album